name: F W
on:
    # push:
    #   branches: 
    #     - main

# We put comment on the main branch

    pull_request:
      branches: 
        - main

jobs:
    read-file:
        runs-on: ubuntu-22.04

        steps:

        - name: Checkout only README.md
          uses: actions/checkout@v6
          with:
            sparse-checkout: |
              README.md
            sparse-checkout-cone-mode: false

        - name: List Files
          run: ls -ltra

        - name: W M
          run: echo "GA W F"

        - name: RF
          run: cat README.md