name: F W
on:
    push

jobs:
    read-file:
        runs-on: ubuntu-latest

        steps:
        - name: C R
          uses: actions/checkout@v6

        - name: W M
          run: echo "GA W F"
    
        - name: LF
          run: ls

        - name: RF
          run: cat README.md