name: Multiple Jobs

on:
    # push:
    #   branches: 
    #     - main

    pull_request:
      branches: 
        - main


jobs: 
    build:
        runs-on: ubuntu-latest
        steps:

        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I'm a DRAGON ... RAWR" >> dragon.txt
        - name: Upload Artifact
          uses: actions/upload-artifact@v7
          with:
           name: my-artifact
           path: dragon.txt
    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: Download Artifact
          uses: actions/download-artifact@v7
          with:
           name: my-artifact

        - name: Test File Exists
          run: grep -i "dragon" dragon.txt

    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:

        - name: Download Artifact
          uses: actions/download-artifact@v7
          with:
           name: my-artifact
           
        - name: Read File
          run: cat dragon.txt

        - name: List Repo Files
          run: ls -ltra