name: ENV

on: 
  push

env:
  COUNTRY: India

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        # - name: Checkout Repo
        #   uses: actions/checkout@v6

        - name: Step1
          env:
            EMP_NAME: Srihari
            EMP_ID: 1393

          run: |
            echo "My Name is $EMP_NAME"
            echo "My Employee ID is $EMP_ID"

        - name: Step2
          # env:
          #   EMP_NAME: Srihari
          #   EMP_ID: 1393

          run: |
            echo "My Name is $EMP_NAME"
            echo "My Employee ID is $EMP_ID"

    second_job:
      runs-on: ubuntu-latest
      env:
        COMPANY: Nuware
        LOCATION: Bengaluru
      steps:
      - name: Job level
        run: echo "My Company is $COMPANY and the Location is $LOCATION"

      - name: Workflow level
        run: echo "My country is $COUNTRY"